package com.snapnote.data.model

import com.snapnote.data.local.entity.KnowledgePointEntity

data class KnowledgePoint(
    val id: Long = 0,
    val noteId: Long,
    val number: String,
    val title: String,
    val content: String,
    val contentType: ContentType,
    val parentId: Long? = null,
    val imageSourceId: Long? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val relations: List<KnowledgePointRelation> = emptyList()
)

data class KnowledgePointRelation(
    val relationId: Long,
    val relatedPoint: KnowledgePoint,
    val relationType: RelationType,
    val strength: String,
    val isAutoGenerated: Boolean
)

fun KnowledgePointEntity.toModel(): KnowledgePoint {
    return KnowledgePoint(
        id = id,
        noteId = noteId,
        number = number,
        title = title,
        content = content,
        contentType = ContentType.fromString(contentType),
        parentId = parentId,
        imageSourceId = imageSourceId,
        createdAt = createdAt
    )
}

fun KnowledgePoint.toEntity(): KnowledgePointEntity {
    return KnowledgePointEntity(
        id = id,
        noteId = noteId,
        number = number,
        title = title,
        content = content,
        contentType = contentType.name,
        parentId = parentId,
        imageSourceId = imageSourceId,
        createdAt = createdAt
    )
}
