package com.snapnote.data.repository

import android.content.Context
import com.snapnote.data.local.AppDatabase
import com.snapnote.data.local.entity.KnowledgePointEntity
import com.snapnote.data.local.entity.RelationEntity
import com.snapnote.data.model.KnowledgePoint
import com.snapnote.data.model.KnowledgePointRelation
import com.snapnote.data.model.RelationType
import com.snapnote.data.model.toEntity
import com.snapnote.data.model.toModel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map

class KnowledgeRepository(context: Context) {
    private val kpDao = AppDatabase.getDatabase(context).knowledgePointDao()
    private val relationDao = AppDatabase.getDatabase(context).relationDao()

    fun getKnowledgePointsByNote(noteId: Long): Flow<List<KnowledgePoint>> {
        return kpDao.getKnowledgePointsByNote(noteId).map { entities ->
            entities.map { it.toModel() }
        }
    }

    fun searchKnowledgePoints(query: String): Flow<List<KnowledgePoint>> {
        return kpDao.searchKnowledgePoints(query).map { entities ->
            entities.map { it.toModel() }
        }
    }

    suspend fun getKnowledgePointWithRelations(id: Long): KnowledgePoint? {
        val kp = kpDao.getKnowledgePointById(id)?.toModel() ?: return null
        val relations = relationDao.getAllRelationsForKnowledgePoint(id).first()
        val relationModels = relations.mapNotNull { rel ->
            val relatedId = if (rel.sourceId == id) rel.targetId else rel.sourceId
            val related = kpDao.getKnowledgePointById(relatedId)?.toModel() ?: return@mapNotNull null
            KnowledgePointRelation(
                relationId = rel.id,
                relatedPoint = related,
                relationType = RelationType.fromString(rel.relationType),
                strength = rel.strength,
                isAutoGenerated = rel.isAutoGenerated
            )
        }
        return kp.copy(relations = relationModels)
    }

    suspend fun saveKnowledgePoints(noteId: Long, points: List<KnowledgePoint>) {
        val entities = points.map { it.toEntity().copy(noteId = noteId) }
        kpDao.insertKnowledgePoints(entities)
    }

    suspend fun addKnowledgePoint(point: KnowledgePoint): Long {
        return kpDao.insertKnowledgePoint(point.toEntity())
    }

    suspend fun updateKnowledgePoint(point: KnowledgePoint) {
        kpDao.updateKnowledgePoint(point.toEntity())
    }

    suspend fun deleteKnowledgePoint(point: KnowledgePoint) {
        kpDao.deleteKnowledgePoint(point.toEntity())
        relationDao.deleteRelationsByKnowledgePoint(point.id)
    }

    suspend fun createRelation(sourceId: Long, targetId: Long, relationType: RelationType, strength: String = "medium", isAuto: Boolean = false) {
        val relation = RelationEntity(
            sourceId = sourceId,
            targetId = targetId,
            relationType = relationType.name,
            strength = strength,
            isAutoGenerated = isAuto
        )
        relationDao.insertRelation(relation)
    }

    suspend fun deleteRelation(relationId: Long) {
        val allRelations = relationDao.getRelationsBySource(0).first()
        val relation = allRelations.find { it.id == relationId }
        relation?.let { relationDao.deleteRelation(it) }
    }
}
